on:
  push:
    branches: [ main ]
    paths:
      - "java/**"
      - ".github/workflows/java-ci.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "java/**"
      - ".github/workflows/java-ci.yml"

jobs:
  build-run-bundle:
    runs-on: [self-hosted, macOS, X64]   # your labels
    defaults:
      run:
        working-directory: java
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle
      - run: chmod +x gradlew
      - run: ./gradlew clean build -x test
      - run: ./gradlew run -x test
      - run: ./gradlew jar -x test
      - uses: actions/upload-artifact@v4
        with:
          name: java-hello-jar
          path: java/build/libs/*.jar
