name: java-ci
on:
  push:
    branches: [ main ]
    paths:
      - "java/**"
      - ".github/workflows/java-ci.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "java/**"
      - ".github/workflows/java-ci.yml"

jobs:
  build-run-bundle:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: java

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build (skip tests)
        run: ./gradlew clean build -x test

      - name: Run application
        run: ./gradlew run -x test

      - name: Package JAR
        run: ./gradlew jar -x test

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-hello-jar
          path: java/build/libs/*.jar
