name: python-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run hello app
        run: python app.py
